config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :oenologists, only:[:new, :create]
  post 'wines', to: 'wines#create'

  root 'wines#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/magazine.rb
class Magazine < ApplicationRecord
    has_many :magazine_oenologists
    has_many :oenologists, through: :magazine_oenologists
end

app/models/magazine_oenologist.rb
class MagazineOenologist < ApplicationRecord
  belongs_to :magazine
  belongs_to :oenologist
end

app/models/oenologist.rb
class Oenologist < ApplicationRecord
    has_many :wine_oenologists
    has_many :magazine_oenologists
    has_many :magazine, through: :magazine_oenologists
    has_many :wines, through: :wine_oenologists
end

app/models/strain.rb
class Strain < ApplicationRecord
    has_many :wine_strains
    has_many :wines, through: :wine_strains 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/wine.rb
class Wine < ApplicationRecord
    has_many :wine_strains
    has_many :wine_oenologists
    has_many :strains, through: :wine_strains
    has_many :oenologists, through: :wine_oenologists

end

app/models/wine_oenologist.rb
class WineOenologist < ApplicationRecord
  belongs_to :wine
  belongs_to :oenologist
end

app/models/wine_strain.rb
class WineStrain < ApplicationRecord
  belongs_to :wine
  belongs_to :strain
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/oenologists_controller.rb
class OenologistsController < ApplicationController
    before_action :authenticate_user!
      def new
          @oenologist = Oenologist.new
          @magazines = Magazine.all
      end
      
      def create
          @oenologist = Oenologist.new(oenologist_params)
          if @oenologist.save
            flash[:success] = "Oenologist successfully created"
            redirect_to root_path
          else
            flash[:error] = "Something went wrong"
            render 'new'
          end
      end
      
      private
      def oenologist_params
          params.require(:oenologist).permit(:name, :age, :nationality, :editor, :writer, :reviewer)
      end
      
  end
  

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :authenticate_user!

    def index
        @wines = Wine.all.includes([:strains, :wine_strains])
        @wine = Wine.new
        @strains = Strain.all
    end

    def create
        @wine = Wine.new(wine_params)
            
        strains_ids = params[:wine][:strain_ids]
        strains_ids.delete("") unless strains_ids.nil?

        strains_percent = params[:wine][:strain_percent]
        strains_percent.delete("") unless strains_percent.nil?

        if @wine.save 
          unless strains_ids.nil?
            strains_ids.length.times do |i| 

              WineStrain.create( 
                wine_id: @wine.id, 
                strain_id: strains_ids[i], 
                percent: strains_percent[i] 
              )
            end
          end

          flash[:success] = "Wine successfully created"
          redirect_to root_path
        else
          flash[:error] = "Something went wrong"
          redirect_to root_path
        end

      
    end

    def edit
      @wine = Wine.find(params[:id])
      @oenologists = Oenologist.all
    end
    
    private
    def wine_params
        params.require(:wine).permit(:name)
    end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cepas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/oenologists/new.html.erb
<h2>Agrega un nuevo enologo</h2>

<%= form_with(model: @oenologist, local: true) do |f| %>

    <div>
        <%= f.label "Nombre" %><br>
        <%= f.text_field :name %> 
    </div><br>

    <div>
        <%= f.label "Age" %><br>
        <%= f.number_field :age %> 
    </div><br>

    <div>
        <%= f.label "Nacionalidad" %><br>
        <%= f.text_field :nationality %> 
    </div><br>
    
    <div>
        <%= f.label "Es editor" %> 
        <%= f.check_box :editor %> <br />
    </div>

    <div>
        <%= f.label "Es escritor" %> 
        <%= f.check_box :writer %> <br />
    </div>

    <div>
        <%= f.label "Es critico" %> 
        <%= f.check_box :reviewer %> <br />
    </div>

    <h3>A que revista pertenece?</h3>

    <% @magazines.each do |magazine| %>
        <div>
            <%= check_box(:oenologist, :magazine_ids, {multiple:true}, magazine.id, nil) %>
            <span><%= magazine.name %></span>
        </div> <br>
    <% end %>
        <%= f.submit %>
<%end%>

app/views/wines/index.html.erb
<% if user_signed_in? %>
    <%= link_to  "Editar perfil", edit_user_registration_path %>
    <%= link_to  "Cerrar sesión", destroy_user_session_path, method: :delete %>
<% else %>
    <%= link_to  "Iniciar sesión", new_user_session_path %>
    <%= link_to  "Registrarse", new_user_registration_path %>
<% end %>

<h1>Registro de cata de vinos</h1>

<% if current_user.admin == true %>
  
    <%= form_with(model: @wine, local: true) do |f|%>
        <div>
            <%= f.label :name %>
            <%= f.text_field :name %>
        </div>

            <% if @strains.count > 0 %>

        <h5>Solo ingresa valores en los campos seleccionados</h5>
            <div>
                <% @strains.each do |strain| %>
                    <div>
                        <%= check_box(:wine, :strain_ids, {multiple:true}, strain.id, nil) %>
                        <span><%= strain.name %></span>
                        <input 
                            type="number"
                            name="wine[strain_percent][]"
                            id="wine_strain_percent_<%= strain.id %>"
                            min="0"
                            max="100"
                            step="1"
                        >
                    </div>
                <% end %>
            </div>
                <% else %>
                    <h5> No hay cepas disponibles </h5>
                <% end %>
                        <div><%= f.submit %></div>
    <% end %>
<% end %>

<h2>Listado de vinos</h2>

<table class='table'>
    <thead>
        <tr>
            <tr>Nombre</tr>
            <tr>Cepas</tr>
        </tr>
    </thead>

    <tbody>
        <% @wines.each do |wine| %>
            <tr>
                <td><%= wine.name %></td>
                    <td>
                        <ul>
                        <% wine.wine_strains.each do |wine_strain|%>
                            <li><%= wine_strain.strain.name %>(<%= wine_strain.percent %>)</li>
                        <% end %>
                        </ul>
                    </td>
            </tr>
        <% end %>
    </tbody>
</table>